### ISSUE TITLE
Duplicated `amsmath`?

### ISSUE THREAD

**Issue by sammo3182** [vincentarelbundock/gtsummary#32]
I'm using the latest github version of `gt` and `gtsummary`.
When compiling a rmd file including `gtsummary`  to latex, it returns an error: 

"! Package mathspec Error: `amsmath' must be loaded earlier than `mathspec'."

It appears that calling `gtsummary` adding `amsmath` at the end of the setting codes when producing the .tex file that caused the problem. When I manually removed `\usepackage{amsmath}`, the file is compilable. Actually, for `bookdown`, it already includes `amsmath` in the default template. Given this case, it may be helpful if there could be an option for `gtsummary` or `knit_latex` to customize the engaged packages---at least `amsmath`.

Here's some example codes:

````
---
title: "example"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: yes
    toc: FALSE
    latex_engine: xelatex
---

```{r}
library(gtsummary)

lm(mpg ~ wt, data = mtcars) %>% gtsummary
```
````

**Comment by vincentarelbundock** [comment]
This is not a `gtsummary` problem. It's upstream somewhere in `knitr` or `rmarkdown`. Look, compilation works with `pdflatex`:
```

---
title: "example"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: yes
    toc: FALSE
    latex_engine: pdflatex
---

```{r}
library(gtsummary)

lm(mpg ~ wt, data = mtcars) %>% gtsummary %>% knit_latex
```
```

**Comment by sammo3182** [comment]
Yep, in the default template of rmarkdown/bookdown, they have `\usepackage{amssymb,amsmath}`. But try this: 

````
---
title: "example"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: yes
    toc: FALSE
    latex_engine: pdflatex
---

```{r}
library(gtsummary)

lm(mpg ~ wt, data = mtcars) %>% gtsummary 
tab_row_group(group = "TEST", rows = 1:2)%>% 
  knit_latex
```
````

I got this error: 

````
! Misplaced \omit.
\multispan ->\omit 
                   \@multispan 
l.172 \multicolumn{1}{l}{TEST}
                               \\ 
````

I'm not sure if changing to `xelatex` could avoid this, but in many cases it appears being more compatible than `pdflatex`. 

Does `gtsummary` added any Latex package, esp. `amsmath`, when compiling the tex files, by the way? I don't have any problem to compile the file (even with `gt` tables), until adding `gtsummary` tables.

**Comment by vincentarelbundock** [comment]
`gtsummary` does *absolutely nothing* to the latex preamble. The only thing it does is touch the `longtable` environment, as follows:

https://github.com/vincentarelbundock/gtsummary/blob/master/R/knit_latex.R

**Comment by sammo3182** [comment]
My bad! Sorry! Just figured out. This issue is caused by `gt` rather than `gtsummary`. My previous trials might include some cache stuff that made the `gt` table compilable w/o problem. Your comments inspired me to trace upstream and found the relevant codes in `gt::utils_render_latex`. I've submitted the issue there (https://github.com/rstudio/gt/issues/280). Sorry for issuing here, again!

**Comment by vincentarelbundock** [comment]
No worries at all. I'm actually quite interested in all this, so it's nice to be kept in the loop :)
