### ISSUE TITLE
Category specification and explanatory note for `table1`

### ISSUE THREAD

**Issue by sammo3182** [vincentarelbundock/gtsummary#33]
Congratulations on the major update of 0.1.0! The `gtsummary` produces the best summary table I've ever used (or created by myself)! 
Two quick question-suggestions: 
1. Is there a way to change the categories of variables without specifying each of them? Something like `mutate_if` in `dplyr`? Also, how does the function distinguish the categorical? Is there a way to customize the rule?
2. The current ways to present the categorical and binaries is excellent! Clear and transparent! For the continuous, though, will that be helpful to add some inline, something like ` 3.15 (min: 0, max: 5)` or an elaborated endnote of the presenting rule?

**Comment by vincentarelbundock** [comment]
Did you mean to file this issue on the gt GitHub? Otherwise, I really don't u derstand your questions ...

**Comment by sammo3182** [comment]
Sorry for the confusion! Allow me to explain it a little bit: In the new function `fmt_table1`, variables will be presented according to their properties (continuous or categorical/binary). You offered a way to customize that with the argument `type` in the current version of the function. What I was looking for was a way to change how  `fmt_table1` treats a whole class of variables. For instance, based on my limited practice of this function, it appears to treat integer vectors with a small number of values as "categorical." So, is there a way that I can ask the function to treat all types of numeric vectors as "continuous," no matter how many types of values it has---a way that I don't have to specify each vector through the `type` argument?

**Comment by vincentarelbundock** [comment]
Sorry, but I still don't understand. `gtsummary` does not offer any `fmt_table1` function.

**Comment by vincentarelbundock** [comment]
oh wow, it looks like somebody stole my package name and released to CRAN

**Comment by sammo3182** [comment]
Wow~ and R package update regards them as the same one...Ok, I'll reinstall it through the github then.

**Comment by vincentarelbundock** [comment]
I never released mine to CRAN because CRAN does not accept github dependencies, and gt is not released to CRAN yet. Meanwhile, the other developers had a table making package, but called different. They seemed to have changed the name in the last couple weeks, and then released to CRAN, effectively preventing me from ever using that name.

I know it's a first come first serve, but it feels like a breach of etiquette to not at least google the name before releasing. It should have been easy to find my package...

In any case, I sent them an email and am waiting to hear.

**Comment by sammo3182** [comment]
I actually didn't realize that until you pointed it out. This is an issue that needs a solution! After reinstalling your package, Rstudio asked me whether "updating" to the 0.1.0 version every time I used its package manager...
